# Generated by Django 4.2.5 on 2023-12-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='user',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
