# Generated by Django 4.2.5 on 2023-12-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_topic_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(default='без должности', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('midname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20)),
                ('date_hired', models.DateField(auto_now_add=True)),
                ('profession', models.ForeignKey(default='без должности', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='professions', to='baseapp.professions', to_field='tittle')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'ordering': ['-date_hired'],
            },
        ),
    ]
