name: test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        touch ti_lox.txt
        sudo apt install wireguard resolvconf
        ls -al
